name: Build Android APK
run-name: ${{ github.event.inputs.repository }} ${{ github.event.inputs.taskName }}

on:
  workflow_dispatch:
    inputs:
      repository:
        description: "Git repository URL"
        required: true
        default: "https://github.com/farizanjum/mixer-1"
      branchName:
        description: "Git branch name [Optional]"
        required: false
        default: ""
      subdir:
        description: "Relative subdirectory path [Optional]"
        required: false
        default: ""
      jdkVersion:
        description: "OpenJDK version"
        required: false
        default: "17"
      taskName:
        description: "build.gradle task name"
        required: false
        default: "assembleDebug"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.2.1

      - name: Clone project
        run: |
          if [[ -z "${{ github.event.inputs.branchName }}" ]]; then
            git clone --recurse-submodules --depth=1 ${{ github.event.inputs.repository }} .
          else
            git clone --recurse-submodules --depth=1 --branch ${{ github.event.inputs.branchName }} ${{ github.event.inputs.repository }} .
          fi

      - name: Build APK
        working-directory: ./${{ github.event.inputs.subdir }}
        run: |
          gradle wrapper
          chmod +x gradlew

          if [[ "${{ github.event.inputs.taskName }}" == *Release* ]]; then
            if [ ! -f "$HOME/.android/debug.keystore" ]; then
              keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
              mkdir -p $HOME/.android
              mv debug.keystore $HOME/.android/debug.keystore
            fi

            ./gradlew ${{ github.event.inputs.taskName }} \
              -Pandroid.injected.signing.store.file="$HOME/.android/debug.keystore" \
              -Pandroid.injected.signing.store.password=android \
              -Pandroid.injected.signing.key.alias=androiddebugkey \
              -Pandroid.injected.signing.key.password=android \
              --stacktrace
          else
            ./gradlew ${{ github.event.inputs.taskName }} --stacktrace
          fi

      - name: Upload the APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-archive
          path: ./**/*.apk
          retention-days: 1
